name: Question
description: Ask a setup, integration, or documentation question
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true
  - type: textarea
    id: attempted
    attributes:
      label: What have you tried?
  - type: textarea
    id: environment
    attributes:
      label: Environment
