import { doublePrecision, integer, jsonb, pgTable, text, timestamp } from "drizzle-orm/pg-core";

export const agentsTable = pgTable("agents", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  type: text("type").notNull(),
  purpose: text("purpose").notNull().default(""),
  permissionLevel: text("permission_level").notNull(),
  status: text("status").notNull(),
  ownerWalletAddress: text("owner_wallet_address").notNull().default(""),
  apiKeyHash: text("api_key_hash").notNull().default(""),
  apiKeyPreview: text("api_key_preview").notNull().default(""),
  apiKeyIssuedAt: timestamp("api_key_issued_at", { withTimezone: true }),
  apiKeyRotatedAt: timestamp("api_key_rotated_at", { withTimezone: true }),
  revokedAt: timestamp("revoked_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const policiesTable = pgTable("policies", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  agentId: text("agent_id").notNull().references(() => agentsTable.id),
  maxTransaction: doublePrecision("max_transaction").notNull(),
  dailyLimit: doublePrecision("daily_limit").notNull(),
  approvalThreshold: doublePrecision("approval_threshold").notNull(),
  trustedContracts: jsonb("trusted_contracts").notNull().default([]),
  blockedActions: jsonb("blocked_actions").notNull().default([]),
  riskMode: text("risk_mode").notNull(),
  status: text("status").notNull(),
  ownerWalletAddress: text("owner_wallet_address").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  policyHash: text("policy_hash").notNull(),
});

export const actionReviewsTable = pgTable("action_reviews", {
  id: text("id").primaryKey(),
  agentId: text("agent_id").notNull(),
  actionType: text("action_type").notNull(),
  amount: doublePrecision("amount").notNull(),
  target: text("target").notNull(),
  targetType: text("target_type").notNull(),
  decision: text("decision").notNull(),
  risk: text("risk").notNull(),
  riskScore: integer("risk_score").notNull(),
  reason: text("reason").notNull(),
  checksPassed: jsonb("checks_passed").notNull().default([]),
  checksFailed: jsonb("checks_failed").notNull().default([]),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const auditLogsTable = pgTable("audit_logs", {
  id: text("id").primaryKey(),
  timestamp: timestamp("timestamp", { withTimezone: true }).notNull().defaultNow(),
  shield: text("shield").notNull(),
  agentId: text("agent_id").notNull(),
  agentName: text("agent_name").notNull(),
  action: text("action").notNull(),
  amount: doublePrecision("amount").notNull(),
  target: text("target").notNull(),
  targetType: text("target_type").notNull(),
  decision: text("decision").notNull(),
  risk: text("risk").notNull(),
  reason: text("reason").notNull(),
  policyUsed: text("policy_used").notNull(),
  walletAddress: text("wallet_address").notNull(),
  agentOwnerWalletAddress: text("agent_owner_wallet_address").notNull().default(""),
  executionWalletAddress: text("execution_wallet_address").notNull().default(""),
  txHash: text("tx_hash").notNull().default(""),
  executionStatus: text("execution_status").notNull().default("not_submitted"),
  executionTxHash: text("execution_tx_hash").notNull().default(""),
  executionSignedBy: text("execution_signed_by").notNull().default(""),
  executionNote: text("execution_note").notNull().default(""),
  executionUpdatedAt: timestamp("execution_updated_at", { withTimezone: true }),
  riskScore: integer("risk_score").notNull(),
});


export const agentGatewayRequestsTable = pgTable("agent_gateway_requests", {
  id: text("id").primaryKey(),
  receivedAt: timestamp("received_at", { withTimezone: true }).notNull().defaultNow(),
  source: text("source").notNull(),
  agentId: text("agent_id").notNull(),
  walletAddress: text("wallet_address").notNull(),
  agentOwnerWalletAddress: text("agent_owner_wallet_address").notNull().default(""),
  executionWalletAddress: text("execution_wallet_address").notNull().default(""),
  actionType: text("action_type").notNull(),
  amount: doublePrecision("amount").notNull(),
  asset: text("asset").notNull().default("CSPR"),
  target: text("target").notNull(),
  targetType: text("target_type").notNull(),
  goal: text("goal").notNull().default(""),
  reason: text("reason").notNull().default(""),
  decision: text("decision").notNull(),
  risk: text("risk").notNull(),
  riskScore: integer("risk_score").notNull(),
  status: text("status").notNull(),
  auditLogId: text("audit_log_id").notNull(),
});
