import { createHash } from 'node:crypto';
import { canonicalThreatIdentity } from './threatIntelligence.mjs';

const OFAC_API_ORIGIN = 'https://api.ofac-api.com';
const DEFAULT_TIMEOUT_MS = 3_500;
const DEFAULT_CACHE_TTL_MS = 5 * 60_000;
const DEFAULT_MAX_RESPONSE_BYTES = 512_000;
const DEFAULT_RATE_LIMIT_PER_MINUTE = 60;
const DEFAULT_FAILURE_THRESHOLD = 3;
const DEFAULT_CIRCUIT_COOLDOWN_MS = 60_000;
const MAX_SUBJECTS = 20;
const cache = new Map();
const runtime = new Map();

function clean(value) { return String(value ?? '').trim(); }
function lower(value) { return clean(value).toLowerCase(); }
function bool(value, fallback = false) { const v = lower(value); if (!v) return fallback; return ['1','true','yes','on'].includes(v); }
function integer(value, fallback, {min=0,max=Number.MAX_SAFE_INTEGER}={}) { const n = Number(value); return Number.isFinite(n) ? Math.min(max, Math.max(min, Math.trunc(n))) : fallback; }
function hashEvidence(value) { return createHash('sha256').update(JSON.stringify(value)).digest('hex'); }
function redact(error) { return clean(error?.message || error).replace(/(api[-_]?key|authorization|token)=?[^&\s]*/gi,'$1=[REDACTED]').slice(0,240) || 'Compliance provider request failed'; }
function providerRuntime(id) { if (!runtime.has(id)) runtime.set(id,{failures:0,circuitOpenUntil:0,windowStart:0,count:0}); return runtime.get(id); }
function rateLimit(id, env, now) { const state=providerRuntime(id); const limit=integer(env.COMPLIANCE_PROVIDER_RATE_LIMIT_PER_MINUTE,DEFAULT_RATE_LIMIT_PER_MINUTE,{min:1,max:10000}); if(now-state.windowStart>=60_000){state.windowStart=now;state.count=0;} state.count+=1; if(state.count>limit){const err=new Error('Compliance provider rate limit reached');err.code='RATE_LIMITED';throw err;} }
function ensureCircuit(id, now) { const state=providerRuntime(id); if(state.circuitOpenUntil>now){const err=new Error('Compliance provider circuit is temporarily open');err.code='CIRCUIT_OPEN';throw err;} }
function noteSuccess(id){const state=providerRuntime(id);state.failures=0;state.circuitOpenUntil=0;}
function noteFailure(id,env,now){const state=providerRuntime(id);state.failures+=1;const threshold=integer(env.COMPLIANCE_PROVIDER_FAILURE_THRESHOLD,DEFAULT_FAILURE_THRESHOLD,{min:1,max:20});if(state.failures>=threshold)state.circuitOpenUntil=now+integer(env.COMPLIANCE_PROVIDER_CIRCUIT_COOLDOWN_MS,DEFAULT_CIRCUIT_COOLDOWN_MS,{min:1000,max:3600000});}

async function readBodyLimited(response,maxBytes){const length=Number(response.headers?.get?.('content-length'));if(Number.isFinite(length)&&length>maxBytes)throw new Error(`Compliance provider response exceeds ${maxBytes} bytes`);if(!response.body||typeof response.body.getReader!=='function'){const raw=await response.text();if(Buffer.byteLength(raw,'utf8')>maxBytes)throw new Error(`Compliance provider response exceeds ${maxBytes} bytes`);return raw;}const reader=response.body.getReader();const decoder=new TextDecoder();let bytes=0,raw='';try{while(true){const {done,value}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>maxBytes){await reader.cancel().catch(()=>{});throw new Error(`Compliance provider response exceeds ${maxBytes} bytes`);}raw+=decoder.decode(value,{stream:true});}raw+=decoder.decode();return raw;}finally{reader.releaseLock();}}
function parseJson(raw){let value;try{value=JSON.parse(raw);}catch{throw new Error('Compliance provider returned malformed JSON');}if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Compliance provider returned an invalid response shape');return value;}

function inferChain(request={}) { const network=lower(request.network || request.chain || request.chainName); const chainId=clean(request.chainId || request.chain_id); if(network.includes('casper') || /^0[12][a-f0-9]{64}$/i.test(clean(request.executionWalletAddress))) return {chainFamily:'casper',chainId:chainId || (network.includes('test')?'casper-test':'')}; if(chainId || /^0x[a-f0-9]{40}$/i.test(clean(request.executionWalletAddress)) || /^0x[a-f0-9]{40}$/i.test(clean(request.target))) return {chainFamily:'evm',chainId:chainId}; return {chainFamily:'unknown',chainId}; }
function subject(value, role, typeHint, chain){ const identity=canonicalThreatIdentity(value,typeHint,{chainId:chain.chainId,chainName:chain.chainId}); if(!identity || !['evm','casper'].includes(identity.chainFamily)) return null; return {role,subjectType:identity.subjectType || identity.kind,identifierKind:identity.kind,canonical:identity.canonical,normalized:identity.normalized || clean(value),chainFamily:identity.chainFamily || chain.chainFamily,chainId:identity.chainId || chain.chainId}; }
export function collectComplianceSubjects(request={}) { const chain=inferChain(request); const candidates=[
  [request.executionWalletAddress || request.walletAddress,'execution-wallet',''],
  [request.target,'recipient-or-contract',request.contractIdentifierType || ''],
  [request.tokenPermissionTokenContract,'token-contract',''],
  [request.bridgeDestinationAddress,'bridge-recipient',''],
  [request.x402PayTo,'x402-recipient',''],
]; const seen=new Set(); return candidates.flatMap(([value,role,typeHint])=>{const item=subject(value,role,typeHint,chain);if(!item||seen.has(item.canonical))return[];seen.add(item.canonical);return[item];}).slice(0,MAX_SUBJECTS); }

export const complianceProviderRegistry=Object.freeze({
  ofac_api: Object.freeze({ id:'ofac_api', name:'OFAC-API Sanctions Screening', version:'v4-screen', authentication:'apiKey-header', capabilities:['wallet-screening','contract-screening','sanctions-related-screening','match-confidence','source-provenance'], subjectTypes:['evm-address','casper-account','casper-account-hash','casper-contract-hash','casper-package-hash'], chainFamilies:['evm','casper','chain-agnostic-identifier'], serverControlledOrigin:OFAC_API_ORIGIN }),
});
function configuredIds(env=process.env){const explicit=clean(env.COMPLIANCE_PROVIDERS);if(explicit)return[...new Set(explicit.split(',').map(lower).filter(Boolean))];return bool(env.COMPLIANCE_OFAC_API_ENABLED,false)?['ofac_api']:[];}
export function getComplianceProviderCapabilities({env=process.env}={}){const enabled=new Set(configuredIds(env));return Object.values(complianceProviderRegistry).map(provider=>{const state=providerRuntime(provider.id);return {...provider,enabled:enabled.has(provider.id),configured:enabled.has(provider.id)&&Boolean(clean(env.COMPLIANCE_OFAC_API_KEY)),health:state.circuitOpenUntil>Date.now()?'degraded':'ready',circuitOpenUntil:state.circuitOpenUntil?new Date(state.circuitOpenUntil).toISOString():''};});}

function normalizeOfacResponse(payload,subject,{now,cached=false,minScore=95}={}){if(payload.error===true)throw new Error(clean(payload.errorMessage)||'OFAC-API reported an error');const results=Array.isArray(payload.results)?payload.results:[];const result=results.find(item=>clean(item?.id)===hashEvidence(subject.canonical).slice(0,24)) || results[0] || {matches:[]};const matches=(Array.isArray(result.matches)?result.matches:[]).slice(0,50).map((match,index)=>{const score=integer(match?.score,0,{min:0,max:100});const sanction=match?.sanction&&typeof match.sanction==='object'?match.sanction:{};const source=clean(sanction.source || sanction.list || sanction.program);return {id:clean(sanction.id)||`match-${index+1}`,category:'sanctions-related',providerSeverity:score>=99?'Critical':score>=95?'High':'Medium',confidence:score,providerClaim:'Potential sanctions-list match returned by provider',source:source||'provider-defined sanctions source',reference:clean(sanction.id),matchFields:Array.isArray(match?.matchSummary?.matchFields)?match.matchSummary.matchFields.slice(0,10).map(field=>({fieldName:clean(field?.fieldName),similarity:clean(field?.similarity)})):[]};});const sourceNames=(Array.isArray(payload.sources)?payload.sources:[]).slice(0,20).map(item=>clean(item?.source||item?.name)).filter(Boolean);const evidenceCore={provider:'OFAC-API',providerId:'ofac_api',providerVersion:'v4-screen',subject:subject.canonical,subjectType:subject.subjectType,subjectRole:subject.role,chainFamily:subject.chainFamily,chainId:subject.chainId,riskCategories:[...new Set(matches.map(item=>item.category))],providerSeverity:matches[0]?.providerSeverity||'None',providerConfidence:matches.length?Math.max(...matches.map(item=>item.confidence)):minScore,providerReference:matches[0]?.reference||'',providerClaim:matches.length?'Provider returned one or more potential sanctions-list matches.':'Provider returned no matches above the configured screening threshold.',evidenceTimestamp:now.toISOString(),evidenceExpiry:new Date(now.getTime()+24*60*60*1000).toISOString(),jurisdictionContext:'provider-defined sanctions datasets',cached,providerDisagreement:false,manualReviewStatus:matches.length?'Suggested':'Not Required',falsePositiveStatus:'Not Assessed',minScore,sources:sourceNames,matches};return {...evidenceCore,evidenceHash:hashEvidence(evidenceCore),providerVerdict:matches.length?'match':'clear'};}

async function screenOfac(subject,{env,fetchImpl,now}){const apiKey=clean(env.COMPLIANCE_OFAC_API_KEY);if(!apiKey){const err=new Error('OFAC-API credentials are unavailable');err.code='AUTH_UNAVAILABLE';throw err;}const nowMs=now.getTime();ensureCircuit('ofac_api',nowMs);rateLimit('ofac_api',env,nowMs);const minScore=integer(env.COMPLIANCE_OFAC_API_MIN_SCORE,95,{min:80,max:100});const cacheKey=`ofac_api|${subject.chainFamily}|${subject.chainId}|${subject.canonical}|${minScore}`;const ttl=integer(env.COMPLIANCE_PROVIDER_CACHE_TTL_MS,DEFAULT_CACHE_TTL_MS,{min:1000,max:24*60*60*1000});const hit=cache.get(cacheKey);if(hit&&nowMs-hit.at<ttl)return {...hit.value,cached:true};const caseId=hashEvidence(subject.canonical).slice(0,24);const body={minScore,cases:[{id:caseId,name:'Blockchain address',cryptoId:subject.normalized}],options:{caseReportPdf:{include:false}}};const timeoutMs=integer(env.COMPLIANCE_PROVIDER_TIMEOUT_MS,DEFAULT_TIMEOUT_MS,{min:250,max:15000});const maxBytes=integer(env.COMPLIANCE_PROVIDER_MAX_RESPONSE_BYTES,DEFAULT_MAX_RESPONSE_BYTES,{min:1024,max:2_000_000});const retries=integer(env.COMPLIANCE_PROVIDER_MAX_RETRIES,1,{min:0,max:2});let lastError;for(let attempt=0;attempt<=retries;attempt+=1){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetchImpl(new URL('/v4/screen',OFAC_API_ORIGIN),{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json',apiKey},body:JSON.stringify(body),signal:controller.signal,redirect:'error'});if(!response.ok)throw new Error(`OFAC-API returned HTTP ${response.status}`);const normalized=normalizeOfacResponse(parseJson(await readBodyLimited(response,maxBytes)),subject,{now,minScore});noteSuccess('ofac_api');cache.set(cacheKey,{at:nowMs,value:normalized});return normalized;}catch(error){lastError=error;if(attempt<retries)await new Promise(resolve=>setTimeout(resolve,Math.min(250*(2**attempt),1000)));}finally{clearTimeout(timer);}}noteFailure('ofac_api',env,nowMs);throw lastError;}

export async function screenComplianceSubjectsWithProviders(subjects=[],{env=process.env,fetchImpl=globalThis.fetch,now=new Date()}={}){const providerIds=configuredIds(env);const providerEvidence=[];const providerStatuses=[];for(const providerId of providerIds){if(providerId!=='ofac_api'){providerStatuses.push({providerId,status:'unsupported',reason:'Unknown compliance provider identifier.'});continue;}if(typeof fetchImpl!=='function'){providerStatuses.push({providerId,status:'unavailable',reason:'Fetch support is unavailable.'});continue;}if(!clean(env.COMPLIANCE_OFAC_API_KEY)){providerStatuses.push({providerId,status:'authentication_unavailable',reason:'Provider credentials are unavailable.'});continue;}for(const item of subjects){try{const evidence=await screenOfac(item,{env,fetchImpl,now});providerEvidence.push(evidence);providerStatuses.push({providerId,status:'available',subject:item.canonical,subjectRole:item.role,cached:evidence.cached===true,verdict:evidence.providerVerdict});}catch(error){const code=error?.name==='AbortError'?'timed_out':error?.code==='RATE_LIMITED'?'rate_limited':error?.code==='CIRCUIT_OPEN'?'degraded':error?.code==='AUTH_UNAVAILABLE'?'authentication_unavailable':'unavailable';providerStatuses.push({providerId,status:code,subject:item.canonical,subjectRole:item.role,reason:redact(error)});}}}
  const bySubject=new Map();for(const evidence of providerEvidence){const list=bySubject.get(evidence.subject)||[];list.push({providerId:evidence.providerId,verdict:evidence.providerVerdict});bySubject.set(evidence.subject,list);}const disagreements=[...bySubject.entries()].flatMap(([subject,entries])=>new Set(entries.map(x=>x.verdict)).size>1?[{subject,entries}]:[]);return {providerIds,providerEvidence,providerStatuses,providerDisagreement:disagreements.length>0,providerDisagreements:disagreements};}
export function resetComplianceProviderRuntime(){cache.clear();runtime.clear();}
