import test from "node:test";
import assert from "node:assert/strict";
import { buildTradingRouteFingerprint, evaluateTradingRouteIntegrity } from "./tradingRouteIntegrity.mjs";

const policy = (overrides = {}) => ({ structuredRules: { tradingRouteIntegrity: { enabled: true, allowedRouters: ["0xrouter"], allowedAggregators: ["agg"], allowedIntermediateAssets: ["weth"], allowedPools: ["pool-1"], allowedFeeRecipients: ["fee-1"], ...overrides } } });
const request = (overrides = {}) => ({ actionType: "Swap", amount: 10, asset: "USDC", outputAsset: "DAI", target: "0xrouter", expectedOutput: 9.9, minimumReceived: 9.8, tradingRouteQuoteProvider: "agg", tradingRouteQuoteId: "q-1", tradingRouteRouter: "0xrouter", tradingRouteAggregator: "agg", tradingRoutePoolSequence: ["pool-1"], tradingRouteTokenPath: ["USDC", "WETH", "DAI"], tradingRouteInputAsset: "USDC", tradingRouteOutputAsset: "DAI", tradingRouteInputAmount: 10, tradingRouteExpectedOutput: 9.9, tradingRouteMinimumOutput: 9.8, tradingRouteFeeBps: 20, tradingRouteFeeRecipients: ["fee-1"], ...overrides });

test("passes an exact approved route", () => { const r = evaluateTradingRouteIntegrity({ request: request(), policy: policy() }); assert.equal(r.hardBlock, false); assert.equal(r.needsReview, false); assert.equal(r.context.status, "passed"); });
test("blocks router mutation", () => { const r = evaluateTradingRouteIntegrity({ request: request({ target: "0xmutated" }), policy: policy() }); assert.equal(r.hardBlock, true); assert.ok(r.findings.some((f) => f.rule === "Router-to-payload binding")); });
test("blocks token path endpoint mismatch", () => { const r = evaluateTradingRouteIntegrity({ request: request({ tradingRouteTokenPath: ["USDC", "WETH", "WBTC"] }), policy: policy() }); assert.equal(r.hardBlock, true); });
test("reviews an unexpected intermediary asset", () => { const r = evaluateTradingRouteIntegrity({ request: request({ tradingRouteTokenPath: ["USDC", "UNKNOWN", "DAI"] }), policy: policy() }); assert.equal(r.needsReview, true); });
test("blocks payload hash mismatch", () => { const r = evaluateTradingRouteIntegrity({ request: request({ tradingRoutePayloadHash: "a".repeat(64), statefulSimulationEvidence: { payloadHash: "b".repeat(64) } }), policy: policy({ requirePayloadBinding: true }) }); assert.equal(r.hardBlock, true); assert.ok(r.findings.some((f) => f.rule === "Quote-to-payload binding")); });
test("detects authorized route mutation", () => { const base = request(); const authorizedRouteHash = buildTradingRouteFingerprint(base); const r = evaluateTradingRouteIntegrity({ request: { ...base, tradingRouteExpectedOutput: 8, tradingRouteAuthorizedRouteHash: authorizedRouteHash }, policy: policy({ requireAuthorizedRouteHash: true }) }); assert.equal(r.hardBlock, true); assert.ok(r.findings.some((f) => f.rule === "Authorized route fingerprint")); });
test("does not apply to transfers", () => { const r = evaluateTradingRouteIntegrity({ request: request({ actionType: "Transfer" }), policy: policy() }); assert.equal(r.context.status, "not_required"); });
test("blocks malformed calldata evidence", () => { const r = evaluateTradingRouteIntegrity({ request: request({ tradingRouteCalldata: "not-hex", tradingRouteCalldataHash: "a".repeat(64) }), policy: policy() }); assert.equal(r.hardBlock, true); assert.ok(r.findings.some((f) => f.evidence?.code === "TRADING_ROUTE_CALLDATA_MALFORMED")); });
test("blocks invalid route hash formats", () => { const r = evaluateTradingRouteIntegrity({ request: request({ tradingRouteAuthorizedRouteHash: "bad-hash" }), policy: policy() }); assert.equal(r.hardBlock, true); assert.ok(r.findings.some((f) => f.evidence?.code === "TRADING_ROUTE_AUTHORIZED_HASH_INVALID")); });
