import test from "node:test";
import assert from "node:assert/strict";
import { evaluateValueExposureLimits, nativeAssetForNetwork, valueExposurePolicy } from "./valueExposureLimits.mjs";

const policy = (valueExposure) => ({ maxTransaction: 30, dailyLimit: 120, approvalThreshold: 20, structuredRules: { valueExposure } });
const base = { actionType: "Transfer", agentId: "A", amount: 0.05, asset: "ETH", executionNetwork: "ethereum", executionWalletAddress: "0xabc", destination: "0xdef" };
const price = { provider: "fixture", assetIdentity: "ethereum:eth", network: "ethereum", price: 3500, referenceCurrency: "USD", timestamp: "2026-08-05T12:00:00.000Z", agreeingSources: 2 };
const now = new Date("2026-08-05T12:00:30.000Z");

test("network registry resolves chain-native assets", () => { assert.equal(nativeAssetForNetwork("Base"), "ETH"); assert.equal(nativeAssetForNetwork("solana"), "SOL"); });
test("legacy policies preserve ambiguous meaning", () => { assert.equal(valueExposurePolicy({ structuredRules: {}, maxTransaction: 30 }).limitBasis, "Legacy Native Amount"); });
test("fiat value below automatic threshold is allowed", () => { const r = evaluateValueExposureLimits({ request: { ...base, amount: 0.01, valueEvidence: price }, policy: policy({ limitBasis: "Fiat Value", automaticLimit: 100, maximumTransactionLimit: 1000 }), now }); assert.equal(r.hardBlock, false); assert.equal(r.needsReview, false); });
test("fiat value above automatic threshold requires review", () => { const r = evaluateValueExposureLimits({ request: { ...base, valueEvidence: price }, policy: policy({ limitBasis: "Fiat Value", automaticLimit: 100, reviewLimit: 100, maximumTransactionLimit: 1000 }), now }); assert.equal(r.needsReview, true); assert.match(r.findings[0].message, /approximately 175.00 USD/); });
test("fiat maximum blocks", () => { const r = evaluateValueExposureLimits({ request: { ...base, amount: .5, valueEvidence: price }, policy: policy({ limitBasis: "Fiat Value", automaticLimit: 100, maximumTransactionLimit: 1000 }), now }); assert.equal(r.hardBlock, true); });
test("stale price never passes", () => { const r = evaluateValueExposureLimits({ request: { ...base, valueEvidence: { ...price, timestamp: "2026-08-05T11:00:00.000Z" } }, policy: policy({ limitBasis: "Fiat Value", maximumTransactionLimit: 1000, maxPriceAgeSeconds: 120 }), now }); assert.equal(r.needsReview, true); assert.match(r.findings[0].message, /stale/); });
test("native policy binds network asset", () => { const r = evaluateValueExposureLimits({ request: base, policy: policy({ limitBasis: "Network Native Asset", maximumTransactionLimit: .1 }), now }); assert.equal(r.hardBlock, false); });
test("wrong native asset blocks", () => { const r = evaluateValueExposureLimits({ request: { ...base, asset: "CSPR" }, policy: policy({ limitBasis: "Network Native Asset", maximumTransactionLimit: 100 }), now }); assert.equal(r.hardBlock, true); });
test("stablecoin depeg is review or block by policy", () => { const req = { ...base, amount: 100, asset: "USDC", assetContractAddress: "0xusdc", valueEvidence: { ...price, assetIdentity: "ethereum:0xusdc", price: .85 } }; const r = evaluateValueExposureLimits({ request: req, policy: policy({ limitBasis: "Fiat Value", maximumTransactionLimit: 1000, stablecoinPeg: { "ethereum:0xusdc": { expectedValue: 1, allowedDeviationPercent: 2, action: "Blocked" } } }), now }); assert.equal(r.hardBlock, true); });
test("pending and uncertain executions count toward daily exposure", () => { const auditLogs = [{ agentId: "A", amount: .04, decision: "Allowed", timestamp: "2026-08-05T11:40:00.000Z", executionStatus: "pending", executionWalletAddress: "0xabc", originalIntent: { executionNetwork: "ethereum", asset: "ETH" }, valueExposureContext: { nativeAmount: .04, assetIdentity: "ethereum:eth" } }]; const r = evaluateValueExposureLimits({ request: base, policy: policy({ limitBasis: "Network Native Asset", maximumTransactionLimit: 1, dailyLimit: .08 }), auditLogs, now }); assert.equal(r.hardBlock, true); assert.equal(r.context.triggeredBreach.rule, "Daily cumulative exposure"); });
test("failed executions do not count", () => { const auditLogs = [{ agentId: "A", amount: .04, timestamp: "2026-08-05T11:40:00.000Z", executionStatus: "failed", executionWalletAddress: "0xabc", originalIntent: { executionNetwork: "ethereum", asset: "ETH" }, valueExposureContext: { nativeAmount: .04, assetIdentity: "ethereum:eth" } }]; const r = evaluateValueExposureLimits({ request: base, policy: policy({ limitBasis: "Network Native Asset", maximumTransactionLimit: 1, dailyLimit: .08 }), auditLogs, now }); assert.equal(r.hardBlock, false); });
